# ailapyu – lightweight local AI service
# OpenAI-compatible API via Ollama

services:
  db:
    image: postgres:16-alpine
    container_name: ailapyu_db
    restart: unless-stopped
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - ailapyu_net

  ollama:
    image: ollama/ollama:latest
    container_name: ailapyu_ollama
    restart: unless-stopped
    environment:
      OLLAMA_HOST: "${OLLAMA_HOST}"
      OLLAMA_NUM_PARALLEL: "${OLLAMA_NUM_PARALLEL}"
      OLLAMA_MAX_LOADED_MODELS: "${OLLAMA_MAX_LOADED_MODELS}"    
      # OLLAMA_NUM_THREADS: "${OLLAMA_NUM_THREADS}"
    volumes:
      - ollama_data:/root/.ollama
    deploy:
      resources:
        limits:
          memory: "${OLLAMA_MEMORY_LIMIT}"
          cpus: "${OLLAMA_CPU_LIMIT}"
    networks:
      - ailapyu_net

  init-model:
    image: ollama/ollama:latest
    container_name: ailapyu_init
    restart: "no"
    depends_on:
      - ollama
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        echo '>>> Waiting for Ollama...'
        until ollama list > /dev/null 2>&1; do sleep 2; done
        echo '>>> Pulling model: ${DEFAULT_MODEL}...'
        ollama pull ${DEFAULT_MODEL}
        echo '>>> Model ready.'
    environment:
      OLLAMA_HOST: "${OLLAMA_INTERNAL_URL}"
    networks:
      - ailapyu_net

  api:
    build:
      context: ./api
    container_name: ailapyu_api
    env_file: .env
    environment:
      OLLAMA_HOST: "${OLLAMA_INTERNAL_URL}"
      OLLAMA_MODEL: "${DEFAULT_MODEL}"
    restart: unless-stopped
    depends_on:
      db:
        condition: service_started
      ollama:
        condition: service_started
      init-model:
        condition: service_completed_successfully

    networks:
      - ailapyu_net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
      - WEB_API_URL=${WEB_API_URL}
    container_name: ailapyu_frontend
    restart: unless-stopped
    depends_on:
      api:
        condition: service_started
    networks:
      - ailapyu_net

  nginx:
    build:
      context: ./proxy
    container_name: ailapyu_nginx
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./proxy/certbot:/etc/letsencrypt
      - ./proxy/www:/var/www/certbot
    depends_on:
      frontend:
          condition: service_started
      api:
        condition: service_started
    networks:
      - ailapyu_net

volumes:
  pg_data:
  ollama_data:
    name: "${OLLAMA_VOLUME}"

networks:
  ailapyu_net:
    driver: bridge